export const DEFAULT_LANGUAGE_PACK = 'es-en-common';

export const LANGUAGE_PACKS = {
  'es-en-common': {
    id: 'es-en-common',
    label: 'Spanish',
    sourceLanguage: 'English',
    targetLanguage: 'Spanish',
    entries: [
      { source: 'Hello', target: 'Hola' },
      { source: 'Hi', target: 'Hola' },
      { source: 'Good morning', target: 'Buenos dias' },
      { source: 'Good afternoon', target: 'Buenas tardes' },
      { source: 'Good evening', target: 'Buenas noches' },
      { source: 'Good night', target: 'Buenas noches' },
      { source: 'How are you?', target: 'Como estas?' },
      { source: 'I am fine', target: 'Estoy bien' },
      { source: 'What is your name?', target: 'Como te llamas?' },
      { source: 'My name is...', target: 'Me llamo...' },
      { source: 'Nice to meet you', target: 'Mucho gusto' },
      { source: 'See you later', target: 'Hasta luego' },
      { source: 'See you tomorrow', target: 'Hasta manana' },
      { source: 'Goodbye', target: 'Adios' },
      { source: 'Welcome', target: 'Bienvenido' },
      { source: 'Please', target: 'Por favor' },
      { source: 'Thank you', target: 'Gracias' },
      { source: 'You are welcome', target: 'De nada' },
      { source: 'Excuse me', target: 'Perdon' },
      { source: 'Sorry', target: 'Lo siento' },
      { source: 'No problem', target: 'No hay problema' },
      { source: 'Yes', target: 'Si' },
      { source: 'No', target: 'No' },
      { source: 'Maybe', target: 'Tal vez' },
      { source: 'Of course', target: 'Por supuesto' },
      { source: 'Who?', target: 'Quien?' },
      { source: 'What?', target: 'Que?' },
      { source: 'When?', target: 'Cuando?' },
      { source: 'Where?', target: 'Donde?' },
      { source: 'Why?', target: 'Por que?' },
      { source: 'How?', target: 'Como?' },
      { source: 'I do not understand', target: 'No entiendo' },
      { source: 'Can you repeat?', target: 'Puede repetir?' },
      { source: 'Speak slowly, please', target: 'Hable despacio, por favor' },
      { source: 'I need help', target: 'Necesito ayuda' },
      { source: 'Help!', target: 'Ayuda!' },
      { source: 'I am lost', target: 'Estoy perdido' },
      { source: 'I am busy', target: 'Estoy ocupado' },
      { source: 'I am tired', target: 'Estoy cansado' },
      { source: 'I am hungry', target: 'Tengo hambre' },
      { source: 'I am thirsty', target: 'Tengo sed' },
      { source: 'I am cold', target: 'Tengo frio' },
      { source: 'I am hot', target: 'Tengo calor' },
      { source: 'I like it', target: 'Me gusta' },
      { source: 'I love it', target: 'Me encanta' },
      { source: 'I do not like it', target: 'No me gusta' },
      { source: 'I agree', target: 'Estoy de acuerdo' },
      { source: 'I disagree', target: 'No estoy de acuerdo' },
      { source: 'Today', target: 'Hoy' },
      { source: 'Tomorrow', target: 'Manana' },
      { source: 'Yesterday', target: 'Ayer' },
      { source: 'Now', target: 'Ahora' },
      { source: 'Later', target: 'Luego' },
      { source: 'Morning', target: 'Manana' },
      { source: 'Afternoon', target: 'Tarde' },
      { source: 'Night', target: 'Noche' },
      { source: 'Minute', target: 'Minuto' },
      { source: 'Hour', target: 'Hora' },
      { source: 'Day', target: 'Dia' },
      { source: 'Week', target: 'Semana' },
      { source: 'Month', target: 'Mes' },
      { source: 'Year', target: 'Ano' },
      { source: 'Monday', target: 'Lunes' },
      { source: 'Tuesday', target: 'Martes' },
      { source: 'Wednesday', target: 'Miercoles' },
      { source: 'Thursday', target: 'Jueves' },
      { source: 'Friday', target: 'Viernes' },
      { source: 'Saturday', target: 'Sabado' },
      { source: 'Sunday', target: 'Domingo' },
      { source: 'January', target: 'Enero' },
      { source: 'February', target: 'Febrero' },
      { source: 'March', target: 'Marzo' },
      { source: 'April', target: 'Abril' },
      { source: 'May', target: 'Mayo' },
      { source: 'June', target: 'Junio' },
      { source: 'July', target: 'Julio' },
      { source: 'August', target: 'Agosto' },
      { source: 'September', target: 'Septiembre' },
      { source: 'October', target: 'Octubre' },
      { source: 'November', target: 'Noviembre' },
      { source: 'December', target: 'Diciembre' },
      { source: 'One', target: 'Uno' },
      { source: 'Two', target: 'Dos' },
      { source: 'Three', target: 'Tres' },
      { source: 'Four', target: 'Cuatro' },
      { source: 'Five', target: 'Cinco' },
      { source: 'Six', target: 'Seis' },
      { source: 'Seven', target: 'Siete' },
      { source: 'Eight', target: 'Ocho' },
      { source: 'Nine', target: 'Nueve' },
      { source: 'Ten', target: 'Diez' },
      { source: 'Eleven', target: 'Once' },
      { source: 'Twelve', target: 'Doce' },
      { source: 'Thirteen', target: 'Trece' },
      { source: 'Fourteen', target: 'Catorce' },
      { source: 'Fifteen', target: 'Quince' },
      { source: 'Sixteen', target: 'Dieciseis' },
      { source: 'Seventeen', target: 'Diecisiete' },
      { source: 'Eighteen', target: 'Dieciocho' },
      { source: 'Nineteen', target: 'Diecinueve' },
      { source: 'Twenty', target: 'Veinte' },
      { source: 'Family', target: 'Familia' },
      { source: 'Friend', target: 'Amigo' },
      { source: 'Man', target: 'Hombre' },
      { source: 'Woman', target: 'Mujer' },
      { source: 'Boy', target: 'Nino' },
      { source: 'Girl', target: 'Nina' },
      { source: 'Child', target: 'Nino' },
      { source: 'Mother', target: 'Madre' },
      { source: 'Father', target: 'Padre' },
      { source: 'Brother', target: 'Hermano' },
      { source: 'Sister', target: 'Hermana' },
      { source: 'Son', target: 'Hijo' },
      { source: 'Daughter', target: 'Hija' },
      { source: 'People', target: 'Gente' },
      { source: 'Everyone', target: 'Todos' },
      { source: 'Water', target: 'Agua' },
      { source: 'Coffee', target: 'Cafe' },
      { source: 'Tea', target: 'Te' },
      { source: 'Milk', target: 'Leche' },
      { source: 'Bread', target: 'Pan' },
      { source: 'Rice', target: 'Arroz' },
      { source: 'Soup', target: 'Sopa' },
      { source: 'Salad', target: 'Ensalada' },
      { source: 'Chicken', target: 'Pollo' },
      { source: 'Fish', target: 'Pescado' },
      { source: 'Meat', target: 'Carne' },
      { source: 'Fruit', target: 'Fruta' },
      { source: 'Vegetable', target: 'Verdura' },
      { source: 'Apple', target: 'Manzana' },
      { source: 'Banana', target: 'Platano' },
      { source: 'Orange', target: 'Naranja' },
      { source: 'Breakfast', target: 'Desayuno' },
      { source: 'Lunch', target: 'Almuerzo' },
      { source: 'Dinner', target: 'Cena' },
      { source: 'Restaurant', target: 'Restaurante' },
      { source: 'House', target: 'Casa' },
      { source: 'Room', target: 'Habitacion' },
      { source: 'Door', target: 'Puerta' },
      { source: 'Window', target: 'Ventana' },
      { source: 'Street', target: 'Calle' },
      { source: 'City', target: 'Ciudad' },
      { source: 'Town', target: 'Pueblo' },
      { source: 'Country', target: 'Pais' },
      { source: 'School', target: 'Escuela' },
      { source: 'Work', target: 'Trabajo' },
      { source: 'Office', target: 'Oficina' },
      { source: 'Store', target: 'Tienda' },
      { source: 'Market', target: 'Mercado' },
      { source: 'Hospital', target: 'Hospital' },
      { source: 'Airport', target: 'Aeropuerto' },
      { source: 'Bus', target: 'Autobus' },
      { source: 'Train', target: 'Tren' },
      { source: 'Car', target: 'Coche' },
      { source: 'Taxi', target: 'Taxi' },
      { source: 'Bicycle', target: 'Bicicleta' },
      { source: 'Left', target: 'Izquierda' },
      { source: 'Right', target: 'Derecha' },
      { source: 'Straight ahead', target: 'Todo recto' },
      { source: 'Near', target: 'Cerca' },
      { source: 'Far', target: 'Lejos' },
      { source: 'Open', target: 'Abrir' },
      { source: 'Close', target: 'Cerrar' },
      { source: 'Start', target: 'Empezar' },
      { source: 'Finish', target: 'Terminar' },
      { source: 'Go', target: 'Ir' },
      { source: 'Come', target: 'Venir' },
      { source: 'Eat', target: 'Comer' },
      { source: 'Drink', target: 'Beber' },
      { source: 'Sleep', target: 'Dormir' },
      { source: 'Read', target: 'Leer' },
      { source: 'Write', target: 'Escribir' },
      { source: 'Listen', target: 'Escuchar' },
      { source: 'Speak', target: 'Hablar' },
      { source: 'Watch', target: 'Mirar' },
      { source: 'Buy', target: 'Comprar' },
      { source: 'Pay', target: 'Pagar' },
      { source: 'Wait', target: 'Esperar' },
      { source: 'Find', target: 'Encontrar' },
      { source: 'Call', target: 'Llamar' },
      { source: 'Can I help you?', target: 'Le puedo ayudar?' },
      { source: 'Can you help me?', target: 'Me puede ayudar?' },
      { source: 'How much is it?', target: 'Cuanto cuesta?' },
      { source: 'It is too expensive', target: 'Es muy caro' },
      { source: 'Do you accept cards?', target: 'Aceptan tarjetas?' },
      { source: 'I would like this', target: 'Quisiera esto' },
      { source: 'The bill, please', target: 'La cuenta, por favor' },
      { source: 'Where is the bathroom?', target: 'Donde esta el bano?' },
      { source: 'Where is the station?', target: 'Donde esta la estacion?' },
      { source: 'Where is the hotel?', target: 'Donde esta el hotel?' },
      { source: 'I have a reservation', target: 'Tengo una reservacion' },
      { source: 'I need a doctor', target: 'Necesito un medico' },
      { source: 'Call the police', target: 'Llame a la policia' },
      { source: 'I feel sick', target: 'Me siento mal' },
      { source: 'I have a headache', target: 'Me duele la cabeza' },
      { source: 'I am allergic to...', target: 'Soy alergico a...' },
      { source: 'Can you take a photo?', target: 'Puede tomar una foto?' },
      { source: 'What time is it?', target: 'Que hora es?' },
      { source: 'See you soon', target: 'Hasta pronto' },
      { source: 'Take care', target: 'Cuidate' },
      { source: 'Have a nice day', target: 'Que tenga un buen dia' },
      { source: 'Good luck', target: 'Buena suerte' },
      { source: 'Congratulations', target: 'Felicidades' },
      { source: 'Happy birthday', target: 'Feliz cumpleanos' },
      { source: 'Cheers!', target: 'Salud!' },
      { source: 'I am learning Spanish', target: 'Estoy aprendiendo espanol' },
      { source: 'Can we practice?', target: 'Podemos practicar?' },
      { source: 'What does this mean?', target: 'Que significa esto?' },
      { source: 'How do you say...?', target: 'Como se dice...?' },
      { source: 'Can you write it down?', target: 'Puede escribirlo?' },
      { source: 'I forgot', target: 'Se me olvido' },
      { source: 'I remember', target: 'Recuerdo' },
      { source: 'Slowly', target: 'Despacio' },
      { source: 'Fast', target: 'Rapido' },
      { source: 'Always', target: 'Siempre' },
      { source: 'Sometimes', target: 'A veces' },
      { source: 'Never', target: 'Nunca' },
      { source: 'Early', target: 'Temprano' },
      { source: 'Late', target: 'Tarde' },
      { source: 'Big', target: 'Grande' },
      { source: 'Small', target: 'Pequeno' },
      { source: 'New', target: 'Nuevo' },
      { source: 'Old', target: 'Viejo' },
      { source: 'Good', target: 'Bueno' },
      { source: 'Bad', target: 'Malo' },
      { source: 'Easy', target: 'Facil' },
      { source: 'Difficult', target: 'Dificil' },
      { source: 'Beautiful', target: 'Bonito' },
      { source: 'Important', target: 'Importante' },
      { source: 'Interesting', target: 'Interesante' },
      { source: 'Ready?', target: 'Listo?' },
      { source: 'I am ready', target: 'Estoy listo' },
      { source: 'Let us go', target: 'Vamos' },
      { source: 'Come with me', target: 'Ven conmigo' },
      { source: 'Turn left', target: 'Gire a la izquierda' },
      { source: 'Turn right', target: 'Gire a la derecha' },
      { source: 'Stop here', target: 'Pare aqui' },
      { source: 'One moment, please', target: 'Un momento, por favor' },
      { source: 'I am sorry for being late', target: 'Perdon por llegar tarde' },
      { source: 'No worries', target: 'No te preocupes' },
      { source: 'That sounds great', target: 'Eso suena genial' },
      { source: 'See you next time', target: 'Hasta la proxima' },
      { source: 'Enjoy your meal', target: 'Buen provecho' },
      { source: 'Welcome back', target: 'Bienvenido de nuevo' },
      { source: 'How was your day?', target: 'Como fue tu dia?' },
      { source: 'My day was good', target: 'Mi dia fue bueno' },
      { source: 'I am at home', target: 'Estoy en casa' },
      { source: 'I am at work', target: 'Estoy en el trabajo' },
      { source: 'I am on my way', target: 'Estoy en camino' },
      { source: 'Can I ask a question?', target: 'Puedo hacer una pregunta?' },
      { source: 'Thanks for your help', target: 'Gracias por tu ayuda' },
      { source: 'Have a good trip', target: 'Buen viaje' },
      { source: 'Safe travels', target: 'Buen viaje' },
      { source: 'Enjoy your weekend', target: 'Disfruta tu fin de semana' },
      { source: 'See you on Monday', target: 'Nos vemos el lunes' },
      { source: 'Happy holidays', target: 'Felices fiestas' },
      { source: 'I miss you', target: 'Te extrano' },
      { source: 'I am proud of you', target: 'Estoy orgulloso de ti' },
      { source: 'Keep going', target: 'Sigue adelante' },
      { source: 'You can do it', target: 'Tu puedes' },
    ],
  },
  'fr-en-common': {
    id: 'fr-en-common',
    label: 'French',
    sourceLanguage: 'English',
    targetLanguage: 'French',
    entries: [
      { source: 'Hello', target: 'Bonjour' },
      { source: 'Hi', target: 'Salut' },
      { source: 'Good morning', target: 'Bonjour' },
      { source: 'Good afternoon', target: 'Bon apres-midi' },
      { source: 'Good evening', target: 'Bonsoir' },
      { source: 'Good night', target: 'Bonne nuit' },
      { source: 'How are you?', target: 'Comment ca va ?' },
      { source: 'I am fine', target: 'Je vais bien' },
      { source: 'What is your name?', target: 'Comment tu t appelles ?' },
      { source: 'My name is...', target: 'Je m appelle...' },
      { source: 'Nice to meet you', target: 'Ravi de vous rencontrer' },
      { source: 'See you later', target: 'A plus tard' },
      { source: 'See you tomorrow', target: 'A demain' },
      { source: 'Goodbye', target: 'Au revoir' },
      { source: 'Welcome', target: 'Bienvenue' },
      { source: 'Please', target: 'S il vous plait' },
      { source: 'Thank you', target: 'Merci' },
      { source: 'You are welcome', target: 'De rien' },
      { source: 'Excuse me', target: 'Excusez-moi' },
      { source: 'Sorry', target: 'Desole' },
      { source: 'No problem', target: 'Pas de probleme' },
      { source: 'Yes', target: 'Oui' },
      { source: 'No', target: 'Non' },
      { source: 'Maybe', target: 'Peut-etre' },
      { source: 'Of course', target: 'Bien sur' },
      { source: 'Who?', target: 'Qui ?' },
      { source: 'What?', target: 'Quoi ?' },
      { source: 'When?', target: 'Quand ?' },
      { source: 'Where?', target: 'Ou ?' },
      { source: 'Why?', target: 'Pourquoi ?' },
      { source: 'How?', target: 'Comment ?' },
      { source: 'I do not understand', target: 'Je ne comprends pas' },
      { source: 'Can you repeat?', target: 'Pouvez-vous repeter ?' },
      { source: 'Speak slowly, please', target: 'Parlez lentement, s il vous plait' },
      { source: 'I need help', target: 'J ai besoin d aide' },
      { source: 'Help!', target: 'Au secours !' },
      { source: 'I am lost', target: 'Je suis perdu' },
      { source: 'I am busy', target: 'Je suis occupe' },
      { source: 'I am tired', target: 'Je suis fatigue' },
      { source: 'I am hungry', target: 'J ai faim' },
      { source: 'I am thirsty', target: 'J ai soif' },
      { source: 'I am cold', target: 'J ai froid' },
      { source: 'I am hot', target: 'J ai chaud' },
      { source: 'I like it', target: 'J aime ca' },
      { source: 'I love it', target: 'J adore ca' },
      { source: 'I do not like it', target: 'Je n aime pas ca' },
      { source: 'Today', target: 'Aujourd hui' },
      { source: 'Tomorrow', target: 'Demain' },
      { source: 'Yesterday', target: 'Hier' },
      { source: 'Now', target: 'Maintenant' },
      { source: 'Later', target: 'Plus tard' },
      { source: 'Water', target: 'Eau' },
      { source: 'Coffee', target: 'Cafe' },
      { source: 'Tea', target: 'The' },
      { source: 'Where is the bathroom?', target: 'Ou sont les toilettes ?' },
      { source: 'How much is it?', target: 'Combien ca coute ?' },
      { source: 'Can you help me?', target: 'Pouvez-vous m aider ?' },
      { source: 'What time is it?', target: 'Quelle heure est-il ?' },
      { source: 'Have a nice day', target: 'Bonne journee' },
      { source: 'I am learning French', target: 'J apprends le francais' },
    ],
  },
  'zh-en-common': {
    id: 'zh-en-common',
    label: 'Mandarin Chinese',
    sourceLanguage: 'English',
    targetLanguage: 'Mandarin Chinese',
    entries: [
      { source: 'Hello', target: '你好' },
      { source: 'Hi', target: '嗨' },
      { source: 'Good morning', target: '早上好' },
      { source: 'Good afternoon', target: '下午好' },
      { source: 'Good evening', target: '晚上好' },
      { source: 'Good night', target: '晚安' },
      { source: 'How are you?', target: '你好吗？' },
      { source: 'I am fine', target: '我很好' },
      { source: 'What is your name?', target: '你叫什么名字？' },
      { source: 'My name is...', target: '我叫...' },
      { source: 'Nice to meet you', target: '很高兴认识你' },
      { source: 'See you later', target: '回头见' },
      { source: 'See you tomorrow', target: '明天见' },
      { source: 'Goodbye', target: '再见' },
      { source: 'Welcome', target: '欢迎' },
      { source: 'Please', target: '请' },
      { source: 'Thank you', target: '谢谢' },
      { source: 'You are welcome', target: '不客气' },
      { source: 'Excuse me', target: '打扰一下' },
      { source: 'Sorry', target: '对不起' },
      { source: 'No problem', target: '没问题' },
      { source: 'Yes', target: '是' },
      { source: 'No', target: '不是' },
      { source: 'Maybe', target: '也许' },
      { source: 'Of course', target: '当然' },
      { source: 'Who?', target: '谁？' },
      { source: 'What?', target: '什么？' },
      { source: 'When?', target: '什么时候？' },
      { source: 'Where?', target: '在哪里？' },
      { source: 'Why?', target: '为什么？' },
      { source: 'How?', target: '怎么？' },
      { source: 'I do not understand', target: '我不明白' },
      { source: 'Can you repeat?', target: '你可以再说一遍吗？' },
      { source: 'Speak slowly, please', target: '请慢一点说' },
      { source: 'I need help', target: '我需要帮助' },
      { source: 'Help!', target: '救命！' },
      { source: 'I am lost', target: '我迷路了' },
      { source: 'I am busy', target: '我很忙' },
      { source: 'I am tired', target: '我累了' },
      { source: 'I am hungry', target: '我饿了' },
      { source: 'I am thirsty', target: '我渴了' },
      { source: 'I am cold', target: '我冷' },
      { source: 'I am hot', target: '我热' },
      { source: 'I like it', target: '我喜欢' },
      { source: 'I love it', target: '我很喜欢' },
      { source: 'I do not like it', target: '我不喜欢' },
      { source: 'Today', target: '今天' },
      { source: 'Tomorrow', target: '明天' },
      { source: 'Yesterday', target: '昨天' },
      { source: 'Now', target: '现在' },
      { source: 'Later', target: '以后' },
      { source: 'Water', target: '水' },
      { source: 'Coffee', target: '咖啡' },
      { source: 'Tea', target: '茶' },
      { source: 'Where is the bathroom?', target: '洗手间在哪里？' },
      { source: 'How much is it?', target: '多少钱？' },
      { source: 'Can you help me?', target: '你能帮我吗？' },
      { source: 'What time is it?', target: '现在几点？' },
      { source: 'Have a nice day', target: '祝你今天愉快' },
      { source: 'I am learning Chinese', target: '我在学中文' },
    ],
  },
  'hi-en-common': {
    id: 'hi-en-common',
    label: 'Hindi',
    sourceLanguage: 'English',
    targetLanguage: 'Hindi',
    entries: [
      { source: 'Hello', target: 'नमस्ते' },
      { source: 'Hi', target: 'हाय' },
      { source: 'Good morning', target: 'सुप्रभात' },
      { source: 'Good afternoon', target: 'नमस्कार' },
      { source: 'Good evening', target: 'शुभ संध्या' },
      { source: 'Good night', target: 'शुभ रात्रि' },
      { source: 'How are you?', target: 'आप कैसे हैं?' },
      { source: 'I am fine', target: 'मैं ठीक हूँ' },
      { source: 'What is your name?', target: 'आपका नाम क्या है?' },
      { source: 'My name is...', target: 'मेरा नाम ... है' },
      { source: 'Nice to meet you', target: 'आपसे मिलकर अच्छा लगा' },
      { source: 'See you later', target: 'फिर मिलते हैं' },
      { source: 'See you tomorrow', target: 'कल मिलते हैं' },
      { source: 'Goodbye', target: 'अलविदा' },
      { source: 'Welcome', target: 'स्वागत है' },
      { source: 'Please', target: 'कृपया' },
      { source: 'Thank you', target: 'धन्यवाद' },
      { source: 'You are welcome', target: 'कोई बात नहीं' },
      { source: 'Excuse me', target: 'माफ कीजिए' },
      { source: 'Sorry', target: 'क्षमा करें' },
      { source: 'No problem', target: 'कोई समस्या नहीं' },
      { source: 'Yes', target: 'हाँ' },
      { source: 'No', target: 'नहीं' },
      { source: 'Maybe', target: 'शायद' },
      { source: 'Of course', target: 'बिल्कुल' },
      { source: 'Who?', target: 'कौन?' },
      { source: 'What?', target: 'क्या?' },
      { source: 'When?', target: 'कब?' },
      { source: 'Where?', target: 'कहाँ?' },
      { source: 'Why?', target: 'क्यों?' },
      { source: 'How?', target: 'कैसे?' },
      { source: 'I do not understand', target: 'मुझे समझ नहीं आया' },
      { source: 'Can you repeat?', target: 'क्या आप दोहरा सकते हैं?' },
      { source: 'Speak slowly, please', target: 'कृपया धीरे बोलिए' },
      { source: 'I need help', target: 'मुझे मदद चाहिए' },
      { source: 'Help!', target: 'मदद!' },
      { source: 'I am lost', target: 'मैं रास्ता भूल गया हूँ' },
      { source: 'I am busy', target: 'मैं व्यस्त हूँ' },
      { source: 'I am tired', target: 'मैं थक गया हूँ' },
      { source: 'I am hungry', target: 'मुझे भूख लगी है' },
      { source: 'I am thirsty', target: 'मुझे प्यास लगी है' },
      { source: 'I am cold', target: 'मुझे ठंड लग रही है' },
      { source: 'I am hot', target: 'मुझे गर्मी लग रही है' },
      { source: 'I like it', target: 'मुझे यह पसंद है' },
      { source: 'I love it', target: 'मुझे यह बहुत पसंद है' },
      { source: 'I do not like it', target: 'मुझे यह पसंद नहीं है' },
      { source: 'Today', target: 'आज' },
      { source: 'Tomorrow', target: 'कल' },
      { source: 'Yesterday', target: 'कल' },
      { source: 'Now', target: 'अभी' },
      { source: 'Later', target: 'बाद में' },
      { source: 'Water', target: 'पानी' },
      { source: 'Coffee', target: 'कॉफी' },
      { source: 'Tea', target: 'चाय' },
      { source: 'Where is the bathroom?', target: 'बाथरूम कहाँ है?' },
      { source: 'How much is it?', target: 'यह कितने का है?' },
      { source: 'Can you help me?', target: 'क्या आप मेरी मदद कर सकते हैं?' },
      { source: 'What time is it?', target: 'कितने बजे हैं?' },
      { source: 'Have a nice day', target: 'आपका दिन शुभ हो' },
      { source: 'I am learning Hindi', target: 'मैं हिंदी सीख रहा हूँ' },
    ],
  },
  'ar-en-common': {
    id: 'ar-en-common',
    label: 'Arabic',
    sourceLanguage: 'English',
    targetLanguage: 'Arabic',
    entries: [
      { source: 'Hello', target: 'مرحبا' },
      { source: 'Hi', target: 'أهلا' },
      { source: 'Good morning', target: 'صباح الخير' },
      { source: 'Good afternoon', target: 'مساء الخير' },
      { source: 'Good evening', target: 'مساء الخير' },
      { source: 'Good night', target: 'تصبح على خير' },
      { source: 'How are you?', target: 'كيف حالك؟' },
      { source: 'I am fine', target: 'أنا بخير' },
      { source: 'What is your name?', target: 'ما اسمك؟' },
      { source: 'My name is...', target: 'اسمي ...' },
      { source: 'Nice to meet you', target: 'تشرفت بمعرفتك' },
      { source: 'See you later', target: 'أراك لاحقاً' },
      { source: 'See you tomorrow', target: 'أراك غداً' },
      { source: 'Goodbye', target: 'مع السلامة' },
      { source: 'Welcome', target: 'أهلاً وسهلاً' },
      { source: 'Please', target: 'من فضلك' },
      { source: 'Thank you', target: 'شكراً' },
      { source: 'You are welcome', target: 'على الرحب والسعة' },
      { source: 'Excuse me', target: 'عفواً' },
      { source: 'Sorry', target: 'أنا آسف' },
      { source: 'No problem', target: 'لا مشكلة' },
      { source: 'Yes', target: 'نعم' },
      { source: 'No', target: 'لا' },
      { source: 'Maybe', target: 'ربما' },
      { source: 'Of course', target: 'بالتأكيد' },
      { source: 'Who?', target: 'من؟' },
      { source: 'What?', target: 'ماذا؟' },
      { source: 'When?', target: 'متى؟' },
      { source: 'Where?', target: 'أين؟' },
      { source: 'Why?', target: 'لماذا؟' },
      { source: 'How?', target: 'كيف؟' },
      { source: 'I do not understand', target: 'أنا لا أفهم' },
      { source: 'Can you repeat?', target: 'هل يمكنك الإعادة؟' },
      { source: 'Speak slowly, please', target: 'تكلم ببطء من فضلك' },
      { source: 'I need help', target: 'أحتاج مساعدة' },
      { source: 'Help!', target: 'النجدة!' },
      { source: 'I am lost', target: 'أنا تائه' },
      { source: 'I am busy', target: 'أنا مشغول' },
      { source: 'I am tired', target: 'أنا متعب' },
      { source: 'I am hungry', target: 'أنا جائع' },
      { source: 'I am thirsty', target: 'أنا عطشان' },
      { source: 'I am cold', target: 'أنا بارد' },
      { source: 'I am hot', target: 'أنا حار' },
      { source: 'I like it', target: 'أعجبني' },
      { source: 'I love it', target: 'أحبه' },
      { source: 'I do not like it', target: 'لا يعجبني' },
      { source: 'Today', target: 'اليوم' },
      { source: 'Tomorrow', target: 'غداً' },
      { source: 'Yesterday', target: 'أمس' },
      { source: 'Now', target: 'الآن' },
      { source: 'Later', target: 'لاحقاً' },
      { source: 'Water', target: 'ماء' },
      { source: 'Coffee', target: 'قهوة' },
      { source: 'Tea', target: 'شاي' },
      { source: 'Where is the bathroom?', target: 'أين الحمام؟' },
      { source: 'How much is it?', target: 'كم سعره؟' },
      { source: 'Can you help me?', target: 'هل يمكنك مساعدتي؟' },
      { source: 'What time is it?', target: 'كم الساعة؟' },
      { source: 'Have a nice day', target: 'أتمنى لك يوماً سعيداً' },
      { source: 'I am learning Arabic', target: 'أنا أتعلم العربية' },
    ],
  },
};

export const LANGUAGE_PACK_OPTIONS = Object.values(LANGUAGE_PACKS).map((pack) => ({
  value: pack.id,
  label: pack.label,
}));

export const getLanguagePack = (packId) =>
  LANGUAGE_PACKS[packId] || LANGUAGE_PACKS[DEFAULT_LANGUAGE_PACK];
